# coding: utf-8

"""
    Querido Diário

    API to access the gazettes from all Brazilian cities  # noqa: E501

    The version of the OpenAPI document: 0.17.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from querido_diario import schemas  # noqa: F401


class GazetteSearchResponse(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "gazettes",
            "total_gazettes",
        }
        
        class properties:
            total_gazettes = schemas.IntSchema
            
            
            class gazettes(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['GazetteItem']:
                        return GazetteItem
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['GazetteItem'], typing.List['GazetteItem']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'gazettes':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'GazetteItem':
                    return super().__getitem__(i)
            __annotations__ = {
                "total_gazettes": total_gazettes,
                "gazettes": gazettes,
            }
    
    gazettes: MetaOapg.properties.gazettes
    total_gazettes: MetaOapg.properties.total_gazettes
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["total_gazettes"]) -> MetaOapg.properties.total_gazettes: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["gazettes"]) -> MetaOapg.properties.gazettes: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["total_gazettes", "gazettes", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["total_gazettes"]) -> MetaOapg.properties.total_gazettes: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["gazettes"]) -> MetaOapg.properties.gazettes: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["total_gazettes", "gazettes", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        gazettes: typing.Union[MetaOapg.properties.gazettes, list, tuple, ],
        total_gazettes: typing.Union[MetaOapg.properties.total_gazettes, decimal.Decimal, int, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'GazetteSearchResponse':
        return super().__new__(
            cls,
            *_args,
            gazettes=gazettes,
            total_gazettes=total_gazettes,
            _configuration=_configuration,
            **kwargs,
        )

from querido_diario.model.gazette_item import GazetteItem
