# coding: utf-8

"""
    Querido Diário

    API to access the gazettes from all Brazilian cities  # noqa: E501

    The version of the OpenAPI document: 0.17.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from querido_diario import schemas  # noqa: F401


class SortBy(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    An enumeration.
    """


    class MetaOapg:
        enum_value_to_name = {
            "relevance": "RELEVANCE",
            "descending_date": "DESCENDING_DATE",
            "ascending_date": "ASCENDING_DATE",
        }
    
    @schemas.classproperty
    def RELEVANCE(cls):
        return cls("relevance")
    
    @schemas.classproperty
    def DESCENDING_DATE(cls):
        return cls("descending_date")
    
    @schemas.classproperty
    def ASCENDING_DATE(cls):
        return cls("ascending_date")
