# coding: utf-8

"""
    Querido Diário

    API to access the gazettes from all Brazilian cities  # noqa: E501

    The version of the OpenAPI document: 0.17.0
    Generated by: https://openapi-generator.tech
"""

from querido_diario.paths.gazettes_by_theme_entities_theme.get import GetAllAvailableEntitiesOfAThemeGazettesByThemeEntitiesThemeGet
from querido_diario.paths.gazettes_by_theme_subthemes_theme.get import GetAllAvailableSubthemesOfAThemeGazettesByThemeSubthemesThemeGet
from querido_diario.paths.gazettes_by_theme_themes_.get import GetAllAvailableThemesGazettesByThemeThemesGet
from querido_diario.paths.cities_territory_id.get import GetCityByIbgeidCitiesTerritoryIdGet
from querido_diario.paths.company_info_cnpj.get import GetCompanyInfoByCnpjNumberCompanyInfoCnpjGet
from querido_diario.paths.company_partners_cnpj.get import GetCompanyPartnersInfosByCnpjNumberCompanyPartnersCnpjGet
from querido_diario.paths.cities.get import SearchForCitiesByNameCitiesGet
from querido_diario.paths.gazettes_by_theme_theme.get import SearchForContentInGazetteExcerptsAssociatedWithAThemeGazettesByThemeThemeGet
from querido_diario.paths.gazettes.get import SearchForContentInGazettesGazettesGet
from querido_diario.paths.suggestions.post import SendASuggestionSuggestionsPost


class DefaultApi(
    GetAllAvailableEntitiesOfAThemeGazettesByThemeEntitiesThemeGet,
    GetAllAvailableSubthemesOfAThemeGazettesByThemeSubthemesThemeGet,
    GetAllAvailableThemesGazettesByThemeThemesGet,
    GetCityByIbgeidCitiesTerritoryIdGet,
    GetCompanyInfoByCnpjNumberCompanyInfoCnpjGet,
    GetCompanyPartnersInfosByCnpjNumberCompanyPartnersCnpjGet,
    SearchForCitiesByNameCitiesGet,
    SearchForContentInGazetteExcerptsAssociatedWithAThemeGazettesByThemeThemeGet,
    SearchForContentInGazettesGazettesGet,
    SendASuggestionSuggestionsPost,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
