# coding: utf-8

"""
    Querido Diário

    API to access the gazettes from all Brazilian cities  # noqa: E501

    The version of the OpenAPI document: 0.17.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import querido_diario
from querido_diario.model.entity import Entity
from querido_diario import configuration


class TestEntity(unittest.TestCase):
    """Entity unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
