# coding: utf-8

# flake8: noqa

"""
    Querido Diário

    API to access the gazettes from all Brazilian cities  # noqa: E501

    The version of the OpenAPI document: 0.17.0
    Generated by: https://openapi-generator.tech
"""

__version__ = "0.0.1"

# import ApiClient
from querido_diario.api_client import ApiClient

# import Configuration
from querido_diario.configuration import Configuration

# import exceptions
from querido_diario.exceptions import OpenApiException
from querido_diario.exceptions import ApiAttributeError
from querido_diario.exceptions import ApiTypeError
from querido_diario.exceptions import ApiValueError
from querido_diario.exceptions import ApiKeyError
from querido_diario.exceptions import ApiException
